const NAV=[['today','⌂','Aujourd’hui'],['calendar','▦','Calendrier'],['tasks','✓','Actions'],['match','⚽','Match Center'],['inbox','⇩','Inbox'],['reports','◫','Reporting'],['settings','⚙','Routines']];
const TEAM=['Amar','Igal','Bastien','Damien','Achraf'];
const defaults=[
{id:1,title:'Valider le menu déplacement Monaco',assignee:'Achraf',priority:'Haute',due:'25 août · 12:00',context:'Monaco – OM',status:'En cours'},
{id:2,title:'Contrôler le cahier des charges hôtel',assignee:'Amar',priority:'Normale',due:'24 août · 17:00',context:'Déplacement',status:'À faire'},
{id:3,title:'Préparer liste matériel déplacement',assignee:'Damien',priority:'Normale',due:'27 août · 14:00',context:'Monaco – OM',status:'À faire'},
{id:4,title:'Relancer les votes repas après-match',assignee:'Bastien',priority:'Haute',due:'28 août · 10:00',context:'Monaco – OM',status:'À faire'},
{id:5,title:'Vérifier modification plan alimentaire',assignee:'Igal',priority:'Normale',due:'Aujourd’hui · 16:00',context:'Nutrition',status:'En cours'}];
const store={get tasks(){return JSON.parse(localStorage.getItem('ops_tasks')||'null')||defaults},set tasks(v){localStorage.setItem('ops_tasks',JSON.stringify(v))},get memos(){return JSON.parse(localStorage.getItem('ops_memos')||'[]')},set memos(v){localStorage.setItem('ops_memos',JSON.stringify(v))}};
let currentPage='today';
function renderNav(){const d=document.getElementById('desktopNav'),m=document.getElementById('mobileNav');const b=([id,ico,label])=>`<button class="nav-item ${id===currentPage?'active':''}" data-page="${id}"><span class="ico">${ico}</span><span>${label}</span></button>`;d.innerHTML=NAV.map(b).join('');m.innerHTML=NAV.slice(0,5).map(b).join('');document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>go(x.dataset.page))}
function go(page){currentPage=page;renderNav();renderPage();window.scrollTo({top:0,behavior:'smooth'})}
function metric(label,value,sub,delta,cls=''){return `<article class="metric-card"><div class="metric-top"><span>${label}</span><span>•••</span></div><h3>${value}</h3><small>${sub} · <span class="delta ${cls}">${delta}</span></small></article>`}
function tagClass(p){return p==='Haute'?'high':p==='Basse'?'low':'normal'}
function taskRow(t){return `<div class="task-row"><button class="check ${t.status==='Terminé'?'done':''}" onclick="toggleTask(${t.id})">${t.status==='Terminé'?'✓':''}</button><div class="task-main"><strong>${t.title}</strong><span>${t.assignee} · ${t.context} · ${t.due}</span></div><span class="tag ${tagClass(t.priority)}">${t.priority}</span></div>`}
function people(name,n){return `<div class="people-line"><strong>${name}</strong><div class="mini-bar"><i style="width:${Math.min(n*20,100)}%"></i></div><span>${n}</span></div>`}
function dashboard(){const t=store.tasks;const alerts=[['#d94d56','Menu Monaco à valider','Validation nutrition attendue avant mardi 12h','J-7'],['#e99a24','23 votes manquants','Repas après-match — clôture vendredi','J-2'],['#1277c7','Travel mis à jour','Horaire retour modifié dans la source Travel','10:42']];return `<div class="hero-grid"><article class="match-hero"><div class="match-meta"><span class="pill">LIGUE 1 · EXTÉRIEUR</span><span class="pill">J-7</span></div><h2>Monaco – OM</h2><p class="sub">Dimanche 30 août · 20:45 · Monaco</p><div class="match-progress"><div class="progress-row"><span>Préparation globale</span><strong>68%</strong></div><div class="progress"><i style="width:68%"></i></div></div></article><article class="alert-panel"><div class="section-head"><h3>À surveiller</h3><span>3 sujets</span></div>${alerts.map(a=>`<div class="attention-item"><i class="attention-dot" style="background:${a[0]}"></i><div><strong>${a[1]}</strong><p>${a[2]}</p></div><time>${a[3]}</time></div>`).join('')}</article></div><div class="cards">${metric('Repas aujourd’hui','68','Déjeuner','+4 vs prévision','good')}${metric('Actions ouvertes',String(t.filter(x=>x.status!=='Terminé').length),'Équipe PRO','2 urgentes','warn')}${metric('Votes après-match','53 / 76','Monaco','70% répondus')}${metric('Déplacement','J-5','Départ précurseur','Hôtel confirmé','good')}</div><div class="two-col"><article class="panel"><div class="section-head"><h3>Priorités du jour</h3><button class="soft-btn" onclick="go('tasks')">Toutes les actions</button></div>${t.slice(0,5).map(taskRow).join('')}</article><article class="panel"><div class="section-head"><h3>Charge équipe</h3><span>Actions ouvertes</span></div><div class="people-bars">${TEAM.map((p,i)=>people(p,[4,3,3,2,2][i])).join('')}</div></article></div>`}
function tasksPage(){const t=store.tasks;return `<div class="list-page-head"><div><p class="eyebrow">ACTIVITÉ ÉQUIPE</p><h2>Actions & To-do</h2></div><div class="filters"><button class="filter-btn active">Toutes</button><button class="filter-btn">Urgentes</button><button class="filter-btn">Mes actions</button><button class="filter-btn">Privées</button></div></div><div class="task-table"><div class="task-table-head"><span></span><span>ACTION</span><span>RESPONSABLE</span><span>PRIORITÉ</span><span>ÉCHÉANCE</span><span>STATUT</span></div>${t.map(x=>`<div class="task-table-row"><button class="check ${x.status==='Terminé'?'done':''}" onclick="toggleTask(${x.id})">${x.status==='Terminé'?'✓':''}</button><div><div class="task-title">${x.title}</div><small>${x.context}${x.private?' · 🔒 privée':''}</small></div><span>${x.assignee}</span><span class="tag ${tagClass(x.priority)}">${x.priority}</span><span>${x.due}</span><span>${x.status}</span></div>`).join('')}</div>`}
function calendarPage(){const days=[['LUN','24'],['MAR','25'],['MER','26'],['JEU','27'],['VEN','28'],['SAM','29'],['DIM','30']],rows=['08:00','10:00','12:00','14:00','16:00','18:00','20:00'],ev={'08:00-1':'<div class="event">Point menu PRO</div>','10:00-2':'<div class="event deadline">Validation Achraf</div>','12:00-0':'<div class="event meal">Déjeuner PRO</div>','12:00-1':'<div class="event meal">Déjeuner PRO</div>','12:00-2':'<div class="event meal">Déjeuner PRO</div>','12:00-3':'<div class="event meal">Déjeuner PRO</div>','12:00-4':'<div class="event meal">Déjeuner PRO</div>','14:00-4':'<div class="event deadline">Clôture votes</div>','16:00-3':'<div class="event">Préparation sacs</div>','18:00-5':'<div class="event">Départ Monaco</div>','20:00-6':'<div class="event match">Monaco – OM · 20:45</div>'};return `<div class="list-page-head"><div><p class="eyebrow">SEMAINE 35</p><h2>Calendrier opérationnel</h2></div><div class="filters"><button class="filter-btn active">Tout</button><button class="filter-btn">Sport</button><button class="filter-btn">Restauration</button><button class="filter-btn">Personnel</button></div></div><div class="calendar-wrap"><div class="calendar"><div class="calendar-head"><div></div>${days.map(d=>`<div>${d[0]}<strong>${d[1]}</strong></div>`).join('')}</div>${rows.map(r=>`<div class="cal-row"><div class="cal-time">${r}</div>${days.map((_,i)=>`<div class="cal-cell">${ev[`${r}-${i}`]||''}</div>`).join('')}</div>`).join('')}</div><aside class="panel"><div class="section-head"><h3>Prochaines échéances</h3></div>${store.tasks.slice(0,4).map(taskRow).join('')}</aside></div>`}
function matchPage(){const items=[['Travel',92],['Nutrition',72],['Menu',60],['Commandes',55],['Après-match',70],['Logistique',61],['Hôtel',85],['Personnel',50]],tl=[['J-7','Menu déplacement','Achraf + Igal'],['J-5','CDC hôtel & Travel','Amar'],['J-4','Commandes','Igal'],['J-3','Matériel & sacs','Damien'],['J-2','Clôture votes','Bastien'],['J-1','Contrôle feuille de route','Amar'],['J','Service & après-match','Équipe']];return `<div class="list-page-head"><div><p class="eyebrow">MATCH CENTER</p><h2>Monaco – OM</h2></div><span class="pill" style="background:#e8f6fc;color:#1675a8">DIM. 30 AOÛT · 20:45</span></div><div class="match-layout"><article class="panel"><div class="section-head"><h3>Niveau de préparation</h3><strong>68%</strong></div><div class="readiness-grid">${items.map(x=>`<div class="readiness"><div class="readiness-head"><span>${x[0]}</span><span>${x[1]}%</span></div><div class="progress"><i style="width:${x[1]}%"></i></div></div>`).join('')}</div></article><aside class="panel"><div class="section-head"><h3>Chronologie</h3><span>automatique</span></div><div class="timeline">${tl.map(x=>`<div class="timeline-item"><span class="day">${x[0]}</span><div class="timeline-line"></div><div><strong>${x[1]}</strong><p>${x[2]}</p></div></div>`).join('')}</div></aside></div>`}
function inboxPage(){const a=[['✉','Travel · Mail','Horaire retour Monaco modifié : arrivée estimée 01:35','À confirmer'],['◉','WhatsApp importé','Feuille de route équipe reçue et reliée au match Monaco','Analysé'],['⌁','Effectif repas','Déjeuner : 68 passages, +4 vs prévision','Info'],['⌂','Audit Hôtel','Audit Monaco disponible — 2 remarques à traiter','Créer actions']];return `<div class="list-page-head"><div><p class="eyebrow">ENTRÉES INTELLIGENTES</p><h2>Inbox opérationnelle</h2></div><div class="filters"><button class="filter-btn active">À traiter</button><button class="filter-btn">Mails</button><button class="filter-btn">WhatsApp</button><button class="filter-btn">Applications</button></div></div><div class="inbox-list">${a.map(x=>`<div class="inbox-card"><div class="source-icon">${x[0]}</div><div><h4>${x[1]}</h4><p>${x[2]}</p></div><span class="action-chip">${x[3]}</span></div>`).join('')}</div>`}
function report(a,b,c,bars){return `<div class="report-card"><span class="eyebrow">${a}</span><h3>${b}</h3><p>${c}</p><div class="spark">${bars.map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div>`}
function reportsPage(){return `<div class="list-page-head"><div><p class="eyebrow">360°</p><h2>Reporting activité</h2></div><div class="filters"><button class="filter-btn active">7 jours</button><button class="filter-btn">30 jours</button></div></div><div class="report-grid">${report('Repas servis','424','+6% vs semaine précédente',[32,44,35,52,61,40,68])}${report('Actions terminées','37','91% dans les délais',[25,31,28,39,42,45,55])}${report('Alertes traitées','12','0 critique ouverte',[50,42,55,38,30,44,25])}</div><article class="panel"><div class="section-head"><h3>Synthèse automatique</h3><span>Dimanche 23 août</span></div><div class="attention-item"><i class="attention-dot" style="background:var(--good)"></i><div><strong>Service PRO stable</strong><p>68 déjeuners aujourd’hui, légèrement au-dessus de la prévision. Aucun incident critique.</p></div></div><div class="attention-item"><i class="attention-dot" style="background:var(--warn)"></i><div><strong>Monaco à sécuriser</strong><p>Validation menu, matériel et clôture des votes restent les trois principaux jalons de la semaine.</p></div></div></article>`}
function settingsPage(){const r=[['Match extérieur','J-10 → J+1','18 étapes'],['Match domicile / Vélodrome','J-7 → J+1','14 étapes'],['Bâtiment PRO quotidien','Chaque jour','8 étapes'],['Veille de match','J-1','7 étapes'],['Après-match','J-3 → J','9 étapes'],['Réunion & décision','À la demande','4 étapes']],s=[['Travel Team Pro','Prévu'],['Effectif Repas','Prévu'],['Audit Hôtel','Prévu'],['Repas Après-Match','Prévu'],['Mail professionnel','Prévu'],['Imports WhatsApp','Prévu']];return `<div class="list-page-head"><div><p class="eyebrow">AUTOMATISATION</p><h2>Routines fixes</h2></div><button class="primary-btn">+ Nouvelle routine</button></div><article class="panel settings-section"><div class="section-head"><h3>Modèles opérationnels</h3><span>les dates suivent automatiquement le match</span></div>${r.map(x=>`<div class="routine-row"><div><strong>${x[0]}</strong><br><span>${x[1]}</span></div><span>${x[2]}</span><span>Relative au match</span><div class="toggle on"></div></div>`).join('')}</article><article class="panel"><div class="section-head"><h3>Sources externes</h3><span>lecture / événements uniquement</span></div>${s.map(x=>`<div class="routine-row"><div><strong>${x[0]}</strong><br><span>Connexion isolée — aucune écriture silencieuse</span></div><span>${x[1]}</span><span>Lecture contrôlée</span><div class="toggle"></div></div>`).join('')}</article>`}
function renderPage(){const meta={today:['DIMANCHE 23 AOÛT','Aujourd’hui'],calendar:['SEMAINE OPÉRATIONNELLE','Calendrier'],tasks:['PILOTAGE ÉQUIPE','Actions'],match:['PROCHAIN MATCH','Match Center'],inbox:['FLUX ENTRANTS','Inbox'],reports:['ACTIVITÉ 360°','Reporting'],settings:['CONFIGURATION','Routines']},pages={today:dashboard,calendar:calendarPage,tasks:tasksPage,match:matchPage,inbox:inboxPage,reports:reportsPage,settings:settingsPage};document.getElementById('pageEyebrow').textContent=meta[currentPage][0];document.getElementById('pageTitle').textContent=meta[currentPage][1];document.getElementById('pageContent').innerHTML=pages[currentPage]()}
function toggleTask(id){store.tasks=store.tasks.map(t=>t.id===id?{...t,status:t.status==='Terminé'?'À faire':'Terminé'}:t);renderPage();toast('Action mise à jour')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
const taskDialog=document.getElementById('taskDialog'),memoDialog=document.getElementById('memoDialog');document.getElementById('taskAssignee').innerHTML=TEAM.map(x=>`<option>${x}</option>`).join('');document.getElementById('quickTaskBtn').onclick=()=>taskDialog.showModal();document.getElementById('quickMemoBtn').onclick=()=>memoDialog.showModal();
document.getElementById('taskForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const title=document.getElementById('taskTitle').value.trim();if(!title)return;const tasks=store.tasks;tasks.unshift({id:Date.now(),title,assignee:document.getElementById('taskAssignee').value,priority:document.getElementById('taskPriority').value,due:document.getElementById('taskDue').value?new Date(document.getElementById('taskDue').value).toLocaleString('fr-FR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Sans échéance',context:document.getElementById('taskContext').value,note:document.getElementById('taskNote').value,private:document.getElementById('taskPrivate').checked,status:'À faire'});store.tasks=tasks;taskDialog.close();e.target.reset();renderPage();toast('Action créée')});
document.getElementById('memoForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const m=store.memos;m.unshift({text:document.getElementById('memoText').value,at:new Date().toISOString()});store.memos=m;memoDialog.close();e.target.reset();toast('Mémo ajouté')});
renderNav();renderPage();